name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - id timestamp
        run: echo "second=$(date +'%S')" >> ${GITHUB_OUTPUT}
      - run: echo "Hello"
        if: ${{ steps.timestamp.outputs.second > 30 }} # ワークフロー実行IDで分岐
