name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - id: timestamp
        run: echo "second=$(date +'%S')" >> ${GITHUB_OUTPUT}
      - env:
          SECOND: ${{ steps.timestamp.outputs.second }}
        run: echo "Hello"
        if: ${{ env.SECOND > 30 }} # ワークフロー実行IDで分岐
